<?php

namespace App\Enum;

enum TypeUsager: string
{
    case CITOYEN = 'CITOYEN';
    case AGENT_PUBLIC = 'AGENT_PUBLIC';
    case PARTENAIRE_TECHNIQUE = 'PARTENAIRE_TECHNIQUE';
    case FOURNISSEUR = 'FOURNISSEUR';
    case STAGIAIRE = 'STAGIAIRE';
    case REPRESENTANT_EXTERNE = 'REPRESENTANT_EXTERNE';
    case VISITEUR_INSTITUTIONNEL = 'VISITEUR_INSTITUTIONNEL';
}
