<?php

namespace App\Enum;

enum TypeActionHistorique: string
{
    case RENDEZ_VOUS_CREE = 'RENDEZ_VOUS_CREE';
    case RENDEZ_VOUS_CONFIRME = 'RENDEZ_VOUS_CONFIRME';
    case RENDEZ_VOUS_REPORTE = 'RENDEZ_VOUS_REPORTE';
    case RENDEZ_VOUS_ANNULE = 'RENDEZ_VOUS_ANNULE';
    case USAGER_NON_PRESENTE = 'USAGER_NON_PRESENTE';
    case ARRIVEE_ENREGISTREE = 'ARRIVEE_ENREGISTREE';
    case VISITE_OUVERTE = 'VISITE_OUVERTE';
    case ORIENTATION_EFFECTUEE = 'ORIENTATION_EFFECTUEE';
    case PRISE_EN_CHARGE_DEMARREE = 'PRISE_EN_CHARGE_DEMARREE';
    case PRISE_EN_CHARGE_CLOTUREE = 'PRISE_EN_CHARGE_CLOTUREE';
    case NOTIFICATION_RECEPTION = 'NOTIFICATION_RECEPTION';
    case DECISION_RECEPTION = 'DECISION_RECEPTION';
    case VISITE_CLOTUREE = 'VISITE_CLOTUREE';
    case PERSONNEL_NON_DISPONIBLE = 'PERSONNEL_NON_DISPONIBLE';
    case DISPONIBILITE_OPERATIONNELLE_CHANGEE = 'DISPONIBILITE_OPERATIONNELLE_CHANGEE';
}
